allow triggering package build via the command line

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -633,6 +633,72 @@ function git_deep_search () {
   fi
 }
 
+
+function git_list_packages () {
+  if [[ -n $GITHUB_OAUTH_TOKEN ]]; then
+    curl -sSL  -H "Authorization: token $GITHUB_OAUTH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
+      https://api.github.com/user/packages?package_type=container \
+      | jq -r '.[] | .repository.full_name,.name' \
+      | sed '$!N;s/\n/:/' \
+      | sort -f
+  else
+    echo "\$GITHUB_OAUTH_TOKEN not defined">&2
+  fi
+}
+
+function git_trigger_repo_dispatch () {
+  if [[ -n $GITHUB_OAUTH_TOKEN ]]; then
+    REPO="$1"
+    echo "Issuing repository_dispatch on $REPO"
+    curl -sSL  -H "Authorization: token $GITHUB_OAUTH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
+      --data '{"event_type": "CLI trigger"}' \
+      "https://api.github.com/repos/$REPO/dispatches"
+  else
+    echo "\$GITHUB_OAUTH_TOKEN not defined">&2
+  fi
+}
+
+function git_trigger_packages_build () {
+  if [[ -n $GITHUB_OAUTH_TOKEN ]]; then
+    # present the menu to our customer and get their selection
+    printf "%s\t%s\n" "0" "ALL"
+    readarray -t PACKAGES < <(git_list_packages)
+    for i in "${!PACKAGES[@]}"; do
+      ((IPLUS=i+1))
+      printf "%s\t%s\n" "$IPLUS" "${PACKAGES[$i]}"
+    done
+    echo -n "Operation:"
+    read USER_FUNCTION_IDX
+
+    if (( $USER_FUNCTION_IDX == 0 )); then
+      unset CONFIRMATION
+      read -p "Are you sure you want to trigger ALL builds? [Y/n]? " CONFIRMATION
+      CONFIRMATION=${CONFIRMATION:-Y}
+      if [[ $CONFIRMATION =~ ^[Yy] ]]; then
+        ALL_REPOS=( "${PACKAGES[@]%:*}" )
+        UNIQUE_REPOS=($(echo "${ALL_REPOS[@]}" | tr ' ' '\n' | grep -v '^null$' | sort -u | tr '\n' ' '))
+        for i in "${!UNIQUE_REPOS[@]}"; do
+          git_trigger_repo_dispatch "${UNIQUE_REPOS[$i]}"
+        done
+      fi
+
+    elif (( $USER_FUNCTION_IDX > 0 )) && (( $USER_FUNCTION_IDX <= "${#PACKAGES[@]}" )); then
+      # execute one function, à la carte
+      USER_FUNCTION="${PACKAGES[((USER_FUNCTION_IDX-1))]}"
+      git_trigger_repo_dispatch "$(echo "$USER_FUNCTION" | cut -d: -f1)"
+
+    else
+      # some people just want to watch the world burn
+      echo "Invalid operation selected">&2
+    fi
+  else
+    echo "\$GITHUB_OAUTH_TOKEN not defined">&2
+  fi
+}
+
+
+
+
 ########################################################################
 # development
 ########################################################################
