added encrypt_file/decrypt_file

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -629,6 +629,32 @@ function umountcrypt() {
   fi
 }
 
+function encrypt_file() {
+  if [[ -n "$1" ]] && [[ -f "$1" ]]; then
+    openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 1024 -salt -in "$1" -out "$1.enc" && \
+      [[ -f "$1.enc" ]] && \
+      ls -l "$1.enc" && \
+      rm -vi "$1"
+  else
+    echo "No file specified, or invalid/nonexistant file" >&2
+  fi
+}
+
+function decrypt_file() {
+  if [[ -n "$1" ]] && [[ -f "$1" ]]; then
+    OUT_FILE="$(echo "$1" | sed "s/\.enc$//")"
+    if [ "$1" = "$OUT_FILE" ]; then
+      OUT_FILE="$1.dec"
+    fi
+    openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 1024 -salt -d -in "$1" -out "$OUT_FILE" && \
+      [[ -f "$OUT_FILE" ]] && \
+      ls -l "$OUT_FILE" && \
+      rm -vi "$1"
+  else
+    echo "No file specified, or invalid/nonexistant file" >&2
+  fi
+}
+
 function dirtydev() {
   while true; do cat /sys/block/$1/stat|cols 9; grep -P "(Dirty)\b" /proc/meminfo; sleep 1; done
 }
